<a href="https://colab.research.google.com/github/Kanika-0905/kanika-codeboosters-2026/blob/main/day_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from sklearn.model_selection import train_test_split
#train_test_split : divides data into training and testing portions
from sklearn.preprocessing import LabelEncoder, StandardScaler
# LabelEncoder: converts text categories to integer (0,1)
# StandardScaler : scales numbers so all features have same range
from sklearn.linear_model import LinearRegression
# LinearRegression : fits a straight-line relationship between features(training) and target (test)
from sklearn.tree import DecisionTreeRegressor
# DesicionTreeRegressor : builds a tree of if/else rules to predict
from sklearn.ensemble import RandomForestRegressor
# RandomForestRegressor : builds 100 desicion tree and average predictions
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
# mean_absolute_error (MAE): average absolute prediction error
# mean_squared_error (MSE): average squared error
# r2_score : model quality score

In [ ]:
df = pd.read_csv('student_performance.csv')
df.describe()
print(f'Dataset Loaded: {df.shape[0]} students,{df.shape[1]} columns')
print(f'columns: {df.columns.tolist()}')
print(f'Missing values: {df.isnull().sum().sum()}')
print("First 5 rows")
df.head()

Dataset Loaded: 30 students,13 columns
columns: ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']
Missing values: 0
First 5 rows

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
print("===ML task===")
print("Target : programming score (the number we want to  predict)")
print(df['programming_score'].describe())

===ML task===
Target : programming score (the number we want to  predict)
count    30.000000
mean     67.600000
std      21.041175
min      38.000000
25%      49.250000
50%      66.000000
75%      88.750000
max      97.000000
Name: programming_score, dtype: float64

In [ ]:
df_ml = df.copy()
le_gender = LabelEncoder()
df_ml['gender_encoded'] = le_gender.fit_transform(df_ml['gender'])
print(f'Gender encoding : {dict(zip(le_gender.classes_,le_gender.transform(le_gender.classes_)))}')
le_dept= LabelEncoder()
df_ml['dept_encoded'] = le_dept.fit_transform(df_ml['department'])
print(f'Department encoding : {dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))}')
df_ml[['gender','gender_encoded','department','dept_encoded']].head(5)

Gender encoding : {'Female': np.int64(0), 'Male': np.int64(1)}
Department encoding : {'Civil': np.int64(0), 'Computer Science': np.int64(1), 'Electronics': np.int64(2), 'Mechanical': np.int64(3)}

   gender  gender_encoded        department  dept_encoded
0    Male               1  Computer Science             1
1  Female               0  Computer Science             1
2    Male               1       Electronics             2
3  Female               0        Mechanical             3
4    Male               1  Computer Science             1

In [ ]:
feature_cols=[
    'math_score',
    'science_score',
    'english_score',
    'attendance_percentage',
    'gender_encoded',
    'dept_encoded'
]
X=df_ml[feature_cols]
Y=df_ml['programming_score']

print(f'Feature matrix X shape : {X.shape} (students x features)')
print(f'Target vector Y shape : {Y.shape} (one score per students)')
print(f'Features : {feature_cols}')
print(f'Target : programming_score')
print(f'Traget range: {Y.max()} to {Y.min()} (mean : {Y.mean()})')

Feature matrix X shape : (30, 6) (students x features)
Target vector Y shape : (30,) (one score per students)
Features : ['math_score', 'science_score', 'english_score', 'attendance_percentage', 'gender_encoded', 'dept_encoded']
Target : programming_score
Traget range: 97 to 38 (mean : 67.6)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(
    X,Y,
    test_size=0.2,
    random_state=42
)
print(f'Total students :{len(X)}')
print(f'Training students : {len(X_train)} ({len(X_train)/len(X)*100 :.0f}%)')
print(f'Testing students : {len(X_test)} ({len(X_test)/len(X)*100:.0f}%)')
print(f'\nTraining target range: {y_train.min()}-{y_train.max()}')
print(f'Testing target range: {y_test.min()}-{y_test.max()}')


print(f'\nTraing feature mean : {X_train.mean()}')
print(f'\nTesting feature std: {X_train.std()}')

Total students :30
Training students : 24 (80%)
Testing students : 6 (20%)

Training target range: 38-96
Testing target range: 39-97

Traing feature mean : math_score               75.458333
science_score            77.458333
english_score            73.416667
attendance_percentage    84.291667
gender_encoded            0.583333
dept_encoded              1.375000
dtype: float64

Testing feature std: math_score               10.786381
science_score             8.500533
english_score             9.504766
attendance_percentage     8.843957
gender_encoded            0.503610
dept_encoded              0.969648
dtype: float64

In [ ]:
lr_model = LinearRegression()
lr_model.fit(X_train,y_train)
lr_pred=lr_model.predict(X_test)
lr_mae=mean_absolute_error(y_test,lr_pred)
lr_rmse=np.sqrt(mean_squared_error(y_test,lr_pred))
lr_r2=r2_score(y_test,lr_pred)
print("=== Linear Regression ===")
print(f'MAE : {lr_mae:.2f}')
print(f'RMSE : {lr_rmse:.2f}') # rmse means when ever the
print(f'R2 :{lr_r2:.4f} ({lr_r2*100:.1f}%)')
print()
print("Learned coefficients")
for feat, coef in zip(feature_cols,lr_model.coef_):
  print(f'{feat:<28}: {coef:+.3f}')
print(f'{"bias (intercept)":<28}:{lr_model.intercept_:+.3f}')

=== Linear Regression ===
MAE : 9.37
RMSE : 11.47
R2 :0.7356 (73.6%)

Learned coefficients
math_score                  : +1.918
science_score               : +0.915
english_score               : +0.257
attendance_percentage       : -1.488
gender_encoded              : -0.804
dept_encoded                : -0.473
bias (intercept)            :-39.891

In [ ]:
dt_tree=DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)
dt_tree.fit(X_train,y_train)
dt_pred=dt_tree.predict(X_test)

dt_mae=mean_absolute_error(y_test,dt_pred)
dt_rmse=np.sqrt(mean_squared_error(y_test,dt_pred))
dt_r2=r2_score(y_test,dt_pred)

print("=== Decision Tree ===")
print(f'MAE : {dt_mae:.2f}')
print(f'RMSE : {dt_rmse:.2f}')
print(f'R2 :{dt_r2:.4f} ({dt_r2*100:.1f}%)')

=== Decision Tree ===
MAE : 9.83
RMSE : 14.76
R2 :0.5623 (56.2%)

In [ ]:
dt_random=RandomForestRegressor(
    max_depth=5,
    random_state=42
)
dt_random.fit(X_train,y_train)
dt_pred=dt_random.predict(X_test)
dt_mae=mean_absolute_error(y_test,dt_pred)
dt_rmse=np.sqrt(mean_squared_error(y_test,dt_pred))
dt_r2=r2_score(y_test,dt_pred)

print("=== Random Forest ===")
print(f'MAE : {dt_mae:.2f}')
print(f'RMSE : {dt_rmse:.2f}')
print(f'R2 :{dt_r2:.4f}')

=== Random Forest ===
MAE : 9.63
RMSE : 12.43
R2 :0.6892